spring.application.name=acadcore-backend

# =========================
# Database Configuration
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/acadcore
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Server Configuration
# =========================
server.port=8080

# =========================
# JWT Configuration
# =========================
jwt.secret=${JWT_SECRET}

# =========================
# Frontend Configuration
# =========================
app.frontend-url=http://localhost:5173

# =========================
# Gmail SMTP Configuration
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Your Gmail address
spring.mail.username=tppatel1809@gmail.com

# Google App Password stored in Windows environment variable
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true